title: ICT Lab
description: Empowering Future Innovators in ICT
logo: "assets/ictlab.png"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

minima:
  skin: classic

header_pages:
  - index.md
  - projects.md

# The cayman-docs theme does not support social_links or footer_text.
# social_links:
#   github: ICT-Lab
footer_text: none
